dist: trusty
language: node_js
node_js:
  - 8
addons:
  apt:
    packages:
      # Needed for Chrome on Trusty
      - libnss3
cache:
  directories:
    - node_modules
before_script:
  - "npm run clean"
  - "npm run build"
script:
  - "npm run test:ci"
