language: node_js
node_js:
  - 13
  - 12
  - 10
  - 8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1
install: yarn install
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - greenkeeper-lockfile-update
  - yarn clean
  - yarn build
after_script: greenkeeper-lockfile-upload

branches:
  only:
    - master
    - /^greenkeeper/.*$/
